# -*- coding: utf-8 -*-
"""Бостонский тест на стрессоустойчивость.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3AJXSvaQ-scgueqxQq5tHt40CeUFQoo
"""

import ipywidgets as widgets
from IPython.display import display

class Questionnaire:
    def __init__(self):
        self.questions = [
            {"question": "Вопрос 1: Вы едите, по крайней мере, одно горячее блюдо в день?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 2: Вы спите 7-8 часов, по крайней мере, 4 раза в неделю?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 3: Вы постоянно чувствуете любовь других и отдаете любовь взамен?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 4: В пределах 50km у Вас есть хотя бы один человек, на которого Вы можете положиться?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 5: Вы упражняетесь до пота хотя бы 2 раза в неделю?",
             "options":["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 6: Вы выкуриваете меньше половины пачки сигарет в день?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 7: За неделю Вы потребляете не больше 5 рюмок крепких алкогольных напитков?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 8: Ваш вес соответствует вашему росту? P.S. Рост(cm) - вес(kg) = 100 - 10",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 9: Ваш доход полностью удовлетворяет ваши основные потребности?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 10: Вас поддерживает Ваша вера?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 11: Вы регулярно занимаетесь клубной или общественной деятельностью?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 12: У Вас много друзей и знакомых?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 13: У Вас есть 1-2 друга, которым Вы полностью доверяете?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 14: Вы здоровы?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 15: Вы можете открыто заявить о своих чувствах, когда Вы злы или обеспокоены чем-либо?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 16: Вы регулярно обсуждаете с людьми, с которыми живете, ваши домашние проблемы?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 17: Вы делаете что-то только ради шутки хотя бы раз в неделю или смеетесь 3 раза в неделю?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 18: Вы можете организовать Ваше время эффективно?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 19: За день Вы потребляете не более 3 чашек кофе, чая или других содержащих кофеин напитков?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]},
            {"question": "Вопрос 20: У Вас есть немного времени для себя в течение каждого дня?",
             "options": ["Всегда", "Часто", "Иногда", "Почти никогда", "Никогда"],
             "weights": [1, 2, 3, 4, 5]}
        ]

        self.answers = [0] * len(self.questions)
        self.current_question_index = 0

        self.label = widgets.Label(value=self.questions[0]["question"])
        self.options = [widgets.RadioButtons(options=self.questions[0]["options"])]
        self.submit_button = widgets.Button(description="Далее")
        self.submit_button.on_click(self.next_question)

        display(self.label)
        display(self.options[0])
        display(self.submit_button)

    def next_question(self, button):
        selected_option = self.options[0].value
        weight_index = self.questions[self.current_question_index]["options"].index(selected_option)
        self.answers[self.current_question_index] = self.questions[self.current_question_index]["weights"][weight_index]

        self.current_question_index += 1

        if self.current_question_index < len(self.questions):
            self.label.value = self.questions[self.current_question_index]["question"]
            self.options[0].options = self.questions[self.current_question_index]["options"]
            self.options[0].value = None
        else:
            self.calculate_result()

    def calculate_result(self):
        total_score = sum(self.answers) - 20
        result = self.get_result(total_score)

        result_label = widgets.Label(value=f"Ваш результат: {result}")
        display(result_label)

    def get_result(self, score):
        if score < 10:
            return "Прекрасная устойчивость к стрессовым ситуациям, здоровью ничто не угрожает"
        elif 11 <= score <= 30:
            return "Нормальный уровень стресса, который соответствует в меру напряженной жизни активного человека"
        elif score > 50:
            return "Человек очень уязвим для стресса, что может негативно отражаться на состоянии здоровья"
        else:
            return "Cтрессовые ситуации сильно влияют на человека, а способности с ними справляться почти нет"

if __name__ == "__main__":
    questionnaire = Questionnaire()